### ISSUE TITLE
Extension Host terminated unexpectedly

### ISSUE THREAD

**Issue by dougrday** [buehler/typescript-hero#367] opened 2017-12-20 19:08 UTC
#### System information

- OS: Windows Version 10.0.14393
- TypeScript Hero version: 1.8.0
- VSCode version: 1.19.0

#### Description

Every time I try TypeScript Hero commands, it fails and eventually notifies me that the Extension Host terminated unexpectedly.

##### Steps to reproduce

1.  Open .ts/.tsx file
2.  Perform TypeScript Hero command (e.g. Ctrl+Alt+O)

Extensions installed:

Beautify 1.1.1
EditorConfig for VS Code 0.11.1
npm 0.3.3
npm Intellisense 1.3.0
TSLint 1.0.24
TypeScript Hero 1.8.0
Visual Studio Team Services 1.122.0

Confirmed to no longer occur when TypeScript Hero is removed/disabled.

**Comment by bwang073** [comment] 2017-12-21 08:54
I met the same problem, Extension Host terminated appears even do nothing, but will work after disable TypeScript Hero. Thought it's a crash level issue.

**Comment by acls** [comment] 2017-12-21 17:38
Same problem. It uses over 100% cpu and then finally crashes. Here's the output from Developer Tools:
```
[Extension Host] debugger inspector at %cFATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
%c 1: node::Abort() [/usr/share/code/libnode.so]
 2: %c0x7f498cf40a57 [/usr/share/code/libnode.so]
 3: %c0x7f498ccdedd7 [/usr/share/code/libnode.so]
 4: %c0x7f498ccded55 [/usr/share/code/libnode.so]
 5: %cv8::internal::Factory::NewByteArray(int, v8::internal::PretenureFlag) [/usr/share/code/libnode.so]
 6: %cv8::internal::SourcePositionTableBuilder::ToSourcePositionTable(v8::internal::Isolate*, v8::internal::Handle<v8::internal::AbstractCode>) [/usr/share/code/libnode.so]
 7: %c0x7f498caaae34 [/usr/share/code/libnode.so]
 8: %c0x7f498caafb11 [/usr/share/code/libnode.so]
 9: %cv8::internal::CompilationJob::ExecuteJob() [/usr/share/code/libnode.so]
10: %c0x7f498c777ee9 [/usr/share/code/libnode.so]
11: %c0x7f498c77b6b8 [/usr/share/code/libnode.so]
12: %c0x7f498c776f14 [/usr/share/code/libnode.so]
13: %cv8::internal::Compiler::Compile(v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Compiler::ClearExceptionFlag) [/usr/share/code/libnode.so]
14: %c0x7f498c99a01e [/usr/share/code/libnode.so]
15: 0x3819ca00437d
%c
<--- Last few GCs --->

[7449:0x17b9c2d2f000]    88790 ms: Mark-sweep 2051.2 (2125.3) -> 2051.2 (2118.8) MB, 1651.0 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 1651 ms) last resort 
[7449:0x17b9c2d2f000]    90442 ms: Mark-sweep 2051.2 (2118.8) -> 2051.2 (2118.8) MB, 1651.3 / 0.0 ms  last resort 


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0xab2f8b2b959 <JS Object>
    2: createChildren [/home/acls/.vscode/extensions/rbbit.typescript-hero-1.8.0/node_modules/typescript/lib/typescript.js:~94901] [pc=0x3819caa1335a](this=0x627e23242e9 <a NodeObject with map 0x1524b113af91>,sourceFile=0x319f15e02311 <undefined>)
    3: getChildren [/home/acls/.vscode/extensions/rbbit.typescript-hero-1.8.0/node_modules/typescript/lib/typescript.js:~94957] [pc=0x3819cc5d56de](th...
```

**Comment by acls** [comment] 2017-12-21 17:39
Looks like this is a duplicate of #363

**Comment by idchlife** [comment] 2017-12-22 19:23
@acls it may be, but I've got this issue just right after last update today.

Same errors:

```javascript
[Extension Host] debugger inspector at %cFATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: %cnode::Abort() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 2: %cnode::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 3: v8::internal::FatalProcessOutOfMemory(char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 4: v8::internal::FatalProcessOutOfMemory(char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 5: %cv8::internal::Factory::NewByteArray(int, v8::internal::PretenureFlag) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 6: %cv8::internal::SourcePositionTableBuilder::ToSourcePositionTable(v8::internal::Isolate*, v8::internal::Handle<v8::internal::AbstractCode>) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 7: v8::internal::Factory::SetClassFunctionInstanceDescriptor(v8::internal::Handle<v8::internal::Map>) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 8: %cv8::internal::Factory::SetClassFunctionInstanceDescriptor(v8::internal::Handle<v8::internal::Map>) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 9: v8::internal::CompilationJob::ExecuteJob() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
10: %cv8::internal::Compiler::EnsureDeoptimizationSupport(v8::internal::CompilationInfo*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
11: v8::internal::Compiler::PostInstantiation(v8::internal::Handle<v8::internal::JSFunction>, v8::internal::PretenureFlag) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
12: %cv8::internal::Compiler::CompileDebugCode(v8::internal::Handle<v8::internal::SharedFunctionInfo>) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
13: v8::internal::Compiler::Compile(v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Compiler::ClearExceptionFlag) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
14: %cv8::internal::RegisterConfiguration::AreAliases(v8::internal::MachineRepresentation, int, v8::internal::MachineRepresentation, int) const [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
15: 0x4725e08437d
16: 0x4725e0846b9
17: 0x4725ec6edfa
%c
<--- Last few GCs --->

[40347:0x7ff90501da00]    90549 ms: Mark-sweep 2052.4 (2139.6) -> 2052.4 (2139.6) MB, 2217.2 / 0.0 ms  allocation failure GC in old space requested
[40347:0x7ff90501da00]    92812 ms: Mark-sweep 2052.4 (2139.6) -> 2052.4 (2117.1) MB, 2262.5 / 0.0 ms  last resort 
[40347:0x7ff90501da00]    95036 ms: Mark-sweep 2052.4 (2117.1) -> 2052.4 (2117.1) MB, 2223.3 / 0.0 ms  last resort 


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x2b950922b959 <JS Object>
    2: createChildren [/Users/igorandreev/.vscode/extensions/rbbit.typescript-hero-1.8.0/node_modules/typescript/lib/typescript.js:~94901] [pc=0x4725ec6edfa](this=0x2d27d4b44661 <a NodeObject with map 0x29a308deb559>,sourceFile=0x3d9c17702311 <undefined>)
    3: getChildren [/Users/igorandreev/.vscode/extensions/rbbit.typescript-hero-1.8.0/node_modules/typescript/lib/typescript.js:~94957] [pc=0...


```

**Comment by acls** [comment] 2017-12-22 19:46
@idchlife I fail to see how that stack trace is different than the stack traces in #363. That issue is still open.

**Comment by pmunin** [comment] 2017-12-26 19:16
Happens on Ubuntu. As far as I understand because of the node's memory limitations

**Comment by buehler** [comment] 2018-01-03 08:35
Sadly a Duplicate of #363

**Closed by buehler** 2018-01-03 08:35 UTC
Labels: bug
