### ISSUE TITLE
Causes VS Code to crash when running npm install from terminal.

### ISSUE THREAD

**Issue by techy2493** [buehler/typescript-hero#86] opened 2016-10-05 14:02 UTC
When running NPM install from the integrated terminal with Typescript Hero installed VS code pops up a window reporting that is is not repsonding and asks the user to restart/wait/close.

Below is the content of the package.json I am trying to install.

{
  "name": "A PROJECT",
  "version": "1.0.0",
  "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/router": "3.0.0",
    "@angular/upgrade": "2.0.0",
    "angular2-in-memory-web-api": "0.0.20",
    "assets-webpack-plugin": "3.4.0",
    "bootstrap-sass": "3.3.7",
    "core-js": "2.4.1",
    "http-server": "0.9.0",
    "ie-shim": "0.1.0",
    "npm-modernizr": "2.8.3",
    "reflect-metadata": "0.1.8",
    "rxjs": "5.0.0-beta.12",
    "systemjs": "0.19.39",
    "zone.js": "0.6.25"
  },
  "devDependencies": {
    "@types/hammerjs": "2.0.33",
    "@types/selenium-webdriver": "2.53.30",
    "@types/source-map": "0.1.27",
    "@types/uglify-js": "2.6.28",
    "@types/webpack": "1.12.34",
    "angular2-template-loader": "0.5.0",
    "awesome-typescript-loader": "2.2.4",
    "codelyzer": "1.0.0-beta.0",
    "concurrently": "3.0.0",
    "copy-webpack-plugin": "3.0.1",
    "css-loader": "0.25.0",
    "exports-loader": "0.6.3",
    "expose-loader": "0.7.1",
    "extract-text-webpack-plugin": "2.0.0-beta.4",
    "file-loader": "0.9.0",
    "html-webpack-plugin": "2.22.0",
    "imports-loader": "0.6.5",
    "istanbul-instrumenter-loader": "1.0.0",
    "jasmine-core": "2.5.2",
    "json-loader": "0.5.4",
    "karma": "1.3.0",
    "karma-chrome-launcher": "2.0.0 ",
    "karma-coverage": "1.1.1",
    "karma-jasmine": "1.0.2",
    "karma-mocha-reporter": "2.2.0",
    "karma-sourcemap-loader": "0.3.7",
    "karma-webpack": "1.8.0",
    "lite-server": "2.2.2",
    "node-sass": "3.10.0",
    "parse5": "2.2.1",
    "raw-loader": "0.5.1",
    "remap-istanbul": "0.6.4",
    "rimraf": "2.5.4",
    "sass-loader": "4.0.2",
    "source-map-loader": "0.1.5",
    "string-replace-loader": "1.0.5",
    "style-loader": "0.13.1",
    "to-string-loader": "1.1.5",
    "ts-helpers": "1.1.1",
    "ts-node": "1.3.0",
    "tslint": "3.15.1",
    "tslint-loader": "2.1.5",
    "typescript": "2.0.3",
    "typings": "1.4.0",
    "url-loader": "0.5.7",
    "webpack": "2.1.0-beta.22",
    "webpack-dev-middleware": "1.8.3",
    "webpack-dev-server": "2.1.0-beta.7",
    "webpack-md5-hash": "0.0.5",
    "webpack-merge": "0.14.1"
  },
  "scripts": {
    "start2": "tsc && concurrently \"npm run tsc:w\" \"npm run lite\" ",
    "lite": "lite-server",
    "postinstall": "typings install",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "typings": "typings",

```
"build:dev": "webpack --config config/webpack.dev.js --progress --profile",
"build:prod": "webpack --config config/webpack.prod.js  --progress --profile --bail",
"build": "npm run build:dev",
"clean:dist": "npm run rimraf -- dist",
"clean:install": "npm set progress=false && npm install",
"clean:start": "npm start",
"clean": "npm cache clean && npm run rimraf -- node_modules doc coverage dist",
"lint": "npm run tslint \"src/**/*.ts\"",
"postversion": "git push && git push --tags",
"prebuild:dev": "npm run clean:dist",
"prebuild:prod": "npm run clean:dist",
"preclean:install": "npm run clean",
"preclean:start": "npm run clean",
"preversion": "npm test",
"rimraf": "rimraf",
"server:dev": "webpack-dev-server --config config/webpack.dev.js --progress --profile --watch --content-base src/",
"server:prod": "http-server dist --cors",
"server": "npm run server:dev",
"start": "npm run server:dev",
"test": "karma start",
"tslint": "tslint",
"watch:dev": "npm run build:dev -- --watch",
"watch:prod": "npm run build:prod -- --watch",
"watch:test": "npm run test -- --auto-watch --no-single-run",
"watch": "npm run watch:dev",
"webdriver-manager": "webdriver-manager",
"webdriver:start": "npm run webdriver-manager start",
"webdriver:update": "npm run webdriver-manager update",
"webpack-dev-server": "webpack-dev-server",
"webpack": "webpack"
```

  }
}

**Comment by buehler** [comment] 2016-10-05 17:42
hmm.. maybe it tries to reindex every downloaded file..
a "quick fix" would be to use an external terminal 😉

**Comment by techy2493** [comment] 2016-10-18 16:19
I wonder if caching would be a suitable resolution to this?

Hash every file, index the hashes, and when it looks at files that appear to be new, compares the hash against it's indexed hash for that file path and if it exists and is the same it does not reindex the file.

**Comment by buehler** [comment] 2016-10-18 18:03
Hey @techy2493 
Hmm actually, that's what it _should_ ™️  do.
I do not hash the files, but tell vscode to deliver the files that are created or changed.
It's this part of the extension: https://github.com/buehler/typescript-hero/blob/master/src/extensions/ResolveExtension.ts#L148-L165

I assume, it's a problem with the `endsWith`. Actually it should filter all files that are not in the workspace itself and filter typings and or node_modules completely. If those whole folders would be ignored, the bug should be solved.

**Comment by buehler** [comment] 2016-10-18 18:05
I'll have a look at it for v0.10 but if you want, I'm more than happy if you have any solution ;-)
I'm currently working on automated testing, but as long as travis does not recognize my test workspace, you have to run the tests locally.

**Comment by buehler** [comment] 2016-11-11 08:16
@techy2493 Does this still exist?
I just tested in 1.7.1 and the filewatcher did not catch an event when files in the node_modules folder changed.

**Comment by buehler** [comment] 2016-11-12 11:33
It did not happen in my vscode :-)
If it still persists, feel free to comment here and I'll reopen it.

**Comment by lilling** [comment] 2016-12-21 23:01
@buehler I work on vscode about 8 months give or take and I ran into this problem just a few days ago...
I run npm install and vscode freeze. only when I restart vscode the npm install run smoothly..

**Comment by asfernandes** [comment] 2017-01-11 11:49
I'm seeing vscode 1.8.1 freezing after run npm or yarn in external terminal in Windows.

**Comment by magnattic** [comment] 2017-02-27 11:37
I have the same problem with Windows 10, VSCode 1.9.1 and TS Hero 0.12.0.

When I run npm install from the console, VS Code hangs and can only be recovered by closing it. When I disable TS hero, it works.

**Comment by kieferrm** [comment] 2017-03-20 18:25
@techy2493, @asfernandes, @magnattic, @lilling, @ktriek has any of you a public github repo that shows the freezing issue? Also, on what platform do you see it.  We are looking into how extensions could cause VS Code freezes/crashes in the context of https://github.com/Microsoft/vscode/issues/22804.

**Comment by ktriek** [comment] 2017-03-20 18:47
@kieferrm the issue seems to be resolved after updating VS Code to the latest version, I have 1.10.2 installed / Windows 7.

**Comment by el-davo** [comment] 2017-03-20 20:59
Seeing the same when doing a an install with yarn. Also hangs when i use a separate terminal outside vscode

**Comment by kimsy** [comment] 2017-05-11 09:09
I am also experiencing this when i build my project with gulp. Crashes everytime. If i disable typescripthero, it works everytime. I will be willing to help out any way I can to resolve this issue

**Comment by lilling** [comment] 2017-05-15 10:51
@kieferrm the issue is not reproduced on my machine anymore.

vs code version: 1.12.1
windows 10

**Comment by el-davo** [comment] 2017-05-28 12:05
Version 1.12.2 fixes this for me 

![image](https://cloud.githubusercontent.com/assets/11195158/26528527/38313a7a-43a6-11e7-8030-e0d9329bc377.png)

**Closed** 2017-05-30 17:20 UTC
Labels: bug
