### ISSUE TITLE
Feature - Import Sort Order

### ISSUE THREAD

**Issue by dukearena** [buehler/typescript-hero#168] opened 2017-02-06 10:47 UTC
#### System information

- OS: Windows 10
- TypeScript Hero version: 0.12.0
- VSCode version: 1.9.0

#### Feature "Import Sort Order"

Would it be possible to auto sort imports first from node_modules, then from my project?
Best choise should be a new setting called "typescriptHero.resolver.importSort" with the following choices:
- NodeModuleFirst
- ProjectFirst

e.g. **NodeModuleFirst**
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs/Rx';
import { MyClass} from '../classes/my-class'

e.g. **ProjectFirst**
import { MyClass} from '../classes/my-class'
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs/Rx';

Note: I'm using angular2 for this example but it could help more kind of project

#### Reason

It's more easy to understand and keep in control all my imports, especially when I change their path. In this case, I don't care about node modules (since they don't chance so fast).

Thank you for your time
Best Regards

**Comment by buehler** [comment] 2017-02-08 06:33
hey @dukearena 
Thanks for the suggestion, the naming may be a bit off, but this is a duplicate of #102 

Cheers

**Closed by buehler** 2017-02-08 06:33 UTC
Labels: duplicate
